version: '3.1'

services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "test1234"
      POSTGRES_USER: "test"
      PGPASSWORD: "test1234"
    volumes:
      - ./data:/var/lib/postgresql/data
