version: '3'

services:
  mongo:
    image: 'mongo:3.6.0'
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - '27017:27017'
    volumes:
      - 'mongo:/data/db'

volumes:
  mongo:
